version: "2.1"
services:
  nginx_hello:
    build: ./nginx-hello
  nginx_goodbye:
    build: ./nginx-goodbye
  nginx_proxy:
    build: ./nginx-proxy
    links:
      - nginx_hello
      - nginx_goodbye
    ports:
      - 80:80
      - 443:443
